apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-gcks
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-gcks
    app.kubernetes.io/part-of: integ-app-urgu
  name: devfile-sample-python-basic-gcks
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-gcks
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-gcks
    spec:
      containers:
      - image: quay.io/bootstrap/integration-e2e-tenant/integ-app-urgu/devfile-sample-python-basic-gcks@sha256:568d34195ea2c99a02b10d507e30b57e4789d151a2f77fe46a45e96320a830a2
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
